biblioteca/urls.py
from usuarios.models import *
from django.contrib.auth.models import User
from django.shortcuts import render_to_response, get_object_or_404
from django.conf.urls import patterns, include, url

from django.contrib import admin
from biblioteca import *

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'biblioteca.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', include('usuarios.urls')),
    url(r'^adquirir_libro/$','usuarios.views.Nuevo'),
    url(r'^devolver_libro/$','usuarios.views.D_Libro'),
    url(r'^admin/', include(admin.site.urls)),

    
    #url(r'^$',usuarios.views.index),


)

usuarios/urls.py
from usuarios.models import *
from django.contrib.auth.models import User
from django.shortcuts import render_to_response, get_object_or_404
from django.conf.urls import patterns, include, url
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('usuarios.views',
		url(r'^$', 'R_Libro'),

		#url(r'^usuarios/$','usuarios.views.adquirir_libro'),
		)

usuarios/models.py
# -*- coding: utf-8 -*-
from django.db import models
#from django.contrib.auth.models import User

# Create your models here.
class Datos(models.Model):
	
	clave = models.CharField(max_length=50)

	def __unicode__(self):
		return self.clave

class RegistroDatos(models.Model):
	fkDatos = models.ForeignKey(Datos)
	Nombre = models.CharField(max_length=50)
	Apellido_Paterno = models.CharField(max_length=50)
	Apellido_Materno = models.CharField(max_length=50)

	def __unicode__(self):
		return u'%s | %s ' % (self.fkDatos, self.nombre)

class Meta:
	verbose_Name=u'Introduce Datos'

class libro(models.Model):
	Matricula = models.CharField(max_length=50)
	Numero_de_Aquisicion = models.CharField(max_length=50)
	Nombre_del_Libro = models.CharField(max_length=50)
	Fecha_de_Salida = models.DateField(max_length=50)
	Entrega = models.DateField(max_length=50)

class Devolver_libro(models.Model):
	Numero_de_Control = models.CharField(max_length=50)
	Numero_de_Aquisicion = models.CharField(max_length=50)
	Salida = models.DateField()
	Entrega = models.DateField()
	Renovaciones = models.CharField(max_length=50)
	Administrativo = models.CharField(max_length=50)

usuarios/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django import forms
from usuarios.models import *

class DatosForm(ModelForm):
	class Meta: 
		model = RegistroDatos

class RegistroLibro(ModelForm):
	class Meta:
		model = libro

class DevolucionLibro(ModelForm):
	class Meta:
		model = Devolver_libro

usuarios/views.py
#from django.shortcuts import render
from usuarios.models import *
from usuarios.forms import *
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext

# Create your views here.
def index(request):
	usuarios = Datos.objects.all()
	return render_to_response('index.html', context_instance=RequestContext(request, locals()))

def ver_detalle(request, id):
	ver = get_object_or_404(Datos, id=id)
	return render_to_response('usuario/ver.html', context_instance=RequestContext(request, locals()))

def adquirir_libro(request):
	Libro = libro.objects.all()



	return render_to_response('adquirir_libro.html', context_instance=RequestContext(request, locals()))

def devolver_libro(request):
	devolver_libr = Devolver_libro.objects.all()
	return render_to_response('devolver_libro.html', context_instance=RequestContext(request, locals()))

def Nuevo(request):
	
	if request.method=='POST':
		formulario = DatosForm(request.POST) #formulario es una variable y DatosForm es el nombre de la clase declarada en forms.py 

		if formulario.is_valid():
			formulario.save()
			return HttpResponseRedirect('adquirir_libro/')

	else:
		formulario = DatosForm()
	
	return render_to_response('adquirir_libro.html',{'formulario':formulario}, context_instance=RequestContext(request))

def R_Libro(request):

	if request.method=='POST':
		registro = RegistroLibro(request.POST)

		if registro.is_valid():
			registro.save()
			return HttpResponseRedirect('/')

	else:
		registro = RegistroLibro()

	return render_to_response('index.html',{'registro':registro}, context_instance=RequestContext(request))

def D_Libro(request):
	if request.method=='POST':
		devolucion = DevolucionLibro(request.POST)

		if devolucion.is_valid():
			devolucion.save()
			return HttpResponseRedirect('devolver_libro/')
	else:
		devolucion = DevolucionLibro()
	return render_to_response('devolver_libro.html',{'devolucion':devolucion}, context_instance=RequestContext(request))

templates/adquirir_libro.html
{% extends 'base.html' %}

{% block titulo %}Adquirir Libro{% endblock %}

{% block contenido %}
	<section class="inner cover">
		<ul>
			<h1 class="cover-heading">Adquirir Libro</h1></br>
			<form id="Registro" method="post" class="lead">{% csrf_token %}
		<ul>
			{{formulario.as_p}}

		</ul>
	
	</form>
		</ul>
	</section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
  <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">   
  <link rel="stylesheet" href="{{STATIC_URL}}jquery-ui-1.11.1.custom/jquery-ui.css">
  <script src="{{STATIC_URL}}jquery-ui-1.11.1.custom/jquery-1.10.2.js"></script>
  <script src="{{STATIC_URL}}jquery-ui-1.11.1.custom/jquery-ui.js"></script>
  

    

    <!-- Bootstrap core CSS -->
    <link href="{{STATIC_URL}}bootstrap-3.2.0-dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{STATIC_URL}}bootstrap-3.2.0-dist/css/cover.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- <script src="../../assets/js/ie-emulation-modes-warning.js"></script>-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Sistema de Bibliotecas</h3>
              <ul class="nav masthead-nav">
                <li class="active"><a href="/"> Prestamos</li></a>
			<li><a href="/adquirir_libro"> Registro </li></a>
			<li><a href="/devolver_libro"> Devoluciones </li></a>
              </ul>
            </div>
          </div>

          {%block contenido%}{%endblock contenido%}
          

          <div class="mastfoot">
            <div class="inner">
              <p>Cover template for <a href="http://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>
    
  </body>
</html>

templates/devolver_libro.html
{% extends 'base.html' %}

{% block titulo %} Devolver Libro {% endblock %}

{% block contenido %}
<script>

  $(function() {
  	
    $( "#id_Salida" ).datepicker();
    $( "#id_Entrega" ).datepicker();
      });
  </script>
	<section class="inner cover">
		<ul>
			<h1 class="cover-heading">Devolver Libro</h1></br>
			<form id="Registro" method="post" class="lead">{% csrf_token %}
		<ul>
			{{devolucion.as_p}}

			<p ><input type="submit" value="Confirmar" class="btn btn-lg btn-default"></p>
		</ul>
	
	</form>
		</ul>
	</section>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block titulo %} Pagina Principal {% endblock %}

{% block contenido %} 
	<section class="inner cover">
		<ul>
			<h1 class="cover-heading">Catalogo</h1></br>
			<form id="Registro" method="post" class="lead">{% csrf_token %}
		<ul>
		<script>
  $(function() {
    $( "#id_Fecha_de_Salida").datepicker();
    $( "#id_Entrega").datepicker();
  });
  </script>
			{{registro.as_p}}
			

			<p ><input type="submit" value="Confirmar" class="btn btn-lg btn-default"></p>
		</ul>
	
	</form>
		</ul>
	</section>
	
 {% endblock %}